### ISSUE TITLE
Problems with textures and text.

### ISSUE THREAD

**Issue by usualenergy299** [nanite/JustHammers#18]
I updated Just hammers mod to the currently newest version for Forge/NeoForge 1.20.1 (just-hammers Forge 2.0.2+mc1.20.1)
and using Architectury ([Forge 1.20(.1)] v9.1.12)
Mod loader is 1.20.1 NeoForge 47.1.84
I tried to check if textures would work in creative and survival, but neither worked for me.
![2023-12-29_20 52 35](https://github.com/ErrorMikey/JustHammers/assets/155188177/6e55fb07-51fa-43ff-a688-9f4a7cc56aa1)
![2023-12-29_20 53 16](https://github.com/ErrorMikey/JustHammers/assets/155188177/a3568d5e-32f0-4553-8938-5e8761933e5b)
![2023-12-29_20 57 18](https://github.com/ErrorMikey/JustHammers/assets/155188177/01735ce2-f33b-4d6e-9708-798013b51370)

**Comment by MichaelHillcox** [comment]
That's hmm... Interesting, I'll give it a try later today and see what might be going on. Maybe I messed something up. Where did you get the mod from? Github, Curseforge or Modrinth?

**Comment by usualenergy299** [comment]
> That's hmm... Interesting, I'll give it a try later today and see what might be going on. Maybe I messed something up. Where did you get the mod from? Github, Curseforge or Modrinth?

I got both mods from Modrinth.
P.S. When I used (just-hammers Forge 2.0.1+mc1.20.1) with the same Architectury version, but with a bit older 1.20.1 NeoForge 47.1.79 mod loader everything was running smoothly.

**Comment by VeraxonHD** [comment]
Heya, I've also encountered this issue. Downloaded from Modrinth version Forge2.0.2+mc1.20.1

**Comment by Zenomoth** [comment]
Same issue, also from Modrinth Forge2.0.2+mc1.20.1

**Comment by MichaelHillcox** [comment]
Should be fixed now https://github.com/nanite/JustHammers/releases/tag/release%2F1.20.1%2F2.0.3

Let me know if it's not
