### ISSUE TITLE
[Issue] no textures

### ISSUE THREAD

**Issue by ChaoscatCJ** [nanite/JustHammers#19]
### Minecraft Version

1.20.1

### Modloader

forge 1.20.1

### Mod version

2.0.3

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

none

### Description of the issue you are having

the items all work just as intended but there is no textures. if i use the 2.0.2 the textures are there.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Are you sure you're on the latest version? 

This is the `2.0.3` version from curseforge found here https://www.curseforge.com/minecraft/mc-mods/justhammers/files/4995650

![](https://c.mikey.pro/scr/8B6wPNMm.png)
