### ISSUE TITLE
[Issue] anyone know what keeps happening i had some mods load however i cant load the recipe mod or this mod dont know what im missing for these to work

### ISSUE THREAD

**Issue by LividTrixx** [nanite/JustHammers#21]
### Minecraft Version

1.20.2

### Modloader

fabric

### Mod version

1.20.2

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

![image_2024-01-05_185742901](https://github.com/nanite/JustHammers/assets/72179429/280fa46c-0337-4987-a91e-6f05c3ce4654)

### Description of the issue you are having

Almost every mod i add always has issues and i manage to find what issues they are. but for this one i just cant find why the recipe mod and this one wont work any idea?? 

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This should be fixed, please let me know if it's not
