### ISSUE TITLE
[Code Question] Looking to do something similar to SelectionOutlineRender.java

### ISSUE THREAD

**Issue by AkitaAttribute** [nanite/JustHammers#24]
### Feature Description

How are you getting LevelRenderer.renderShape to work in your class?  It's private when I am attempting to use it.

**Comment by MichaelHillcox** [comment]
https://github.com/nanite/JustHammers/blob/main/common/src/main/resources/justhammers.accesswidener

Hope this helps 

https://fabricmc.net/wiki/tutorial:accesswideners

https://docs.minecraftforge.net/en/latest/advanced/accesstransformers/

**Comment by AkitaAttribute** [comment]
> https://github.com/nanite/JustHammers/blob/main/common/src/main/resources/justhammers.accesswidener
> 
> Hope this helps
> 
> https://fabricmc.net/wiki/tutorial:accesswideners
> 
> https://docs.minecraftforge.net/en/latest/advanced/accesstransformers/

I totally missed that, thanks a bunch.
