### ISSUE TITLE
Minus Durability

### ISSUE THREAD

**Issue by Gamefreaknet** [nanite/JustHammers#27]
### Minecraft Version

1.20.1

### Modloader

Fabric 0.15.11

### Mod version

justhammers-fabric-2.0.3+mc1.20.1.jar

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[crash-2024-06-11_01.34.13-client.txt](https://github.com/user-attachments/files/15780956/crash-2024-06-11_01.34.13-client.txt)
[crash-2024-06-11_01.58.20-client.txt](https://github.com/user-attachments/files/15780957/crash-2024-06-11_01.58.20-client.txt)

### Steps to reproduce the issue

1. Get 2 hammers (mine was stone) and get them to a durability value of 0
2. Merge them in the 2x2 crafting grid to restore some of their durability
3. (Inconsistent result) Hammer might appear with a -dura value and client might crash with the below error to the launcher
![image](https://github.com/nanite/JustHammers/assets/144167275/8d97a4bc-0736-4457-a250-a23e5ef1db24)
![image](https://github.com/nanite/JustHammers/assets/144167275/a458f509-ab29-4da8-8263-bbfa807aba72)

### Description of the issue you are having

(Mods that could've also caused issues):
Marium's Soulslike Weaponry
The first crash report is the original time the error occurred which caused the -dura value and the second report in case the crash was somehow different.
I originally thought this was purely clientside however after consulting my friend (server owner) he also confirmed there were data issues/errors that came up in the server log around the time I merged 2 of the hammers to repair them. 
(BisectHosting Premium 16GB - I can get him to try retrieve the logs from the server if they would also help)
My game crashed 3 seconds later and upon relaunching would only crash if I hovered my mouse over the hammer, tried to move it or do anything with it at all to move it, delete it or something else (I managed to get rid of it though).

Note: I did notice although in this case I couldn't get another to minus durability when I did merge 2 hammers at 0 durability they actually somehow restored 50% durability somehow?

Modpack: Prominence II [RPG] V-2.8.6hf

### Information

- [X] I have provided as much information as possible

**Comment by thisRedH** [comment]
Same as #23
