### ISSUE TITLE
[Issue] Can't see hammers recipes in REI

### ISSUE THREAD

**Issue by Ambulanza** [nanite/JustHammers#28]
### Minecraft Version

1.21.0

### Modloader

Fabric 0.15.11-1.21

### Mod version

just-hammers-fabric-21.0.0

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

I don not have any log files for this issue

### Steps to reproduce the issue

1. Open world
2. open inventory or crafting table
3. search for hammers
4. click on one
5. no recipe showing, only anvil

### Description of the issue you are having

Hi, i can't seem to make the justhammers mod work. I have everything on the latest version, loader included.
I have both architectury and cloth-config. I am playing in singleplayer in java version, i can see hammers in REI, but if i click on them it only shows the repairing on the anvil and not the building recipe. I can't also seem to build one (i looked at a screenshot in an old post with the stone hammer, didn't work). Did i miss some other mod i need to install? Thank you in advance for any answer.
![2024-06-16_23 51 33](https://github.com/nanite/JustHammers/assets/173003835/fdf7c090-04fe-4389-ae61-cacbb225a0fc)
![2024-06-16_23 51 38](https://github.com/nanite/JustHammers/assets/173003835/b67f5194-6b66-47c1-b01d-3fcc2af4327a)
![2024-06-16_23 58 47](https://github.com/nanite/JustHammers/assets/173003835/99218cb4-9df8-4b0e-b9bf-35823934826d)
![2024-06-17_00 00 40](https://github.com/nanite/JustHammers/assets/173003835/75eef8ea-b945-4975-809c-a77a8701419d)

### Information

- [X] I have provided as much information as possible

**Comment by JCSiders** [comment]
Hello, this exact same issue is happening with me on my 1.21 server, is there a list of the crafting recipes somewhere so we can still use the mod even though JEI isn't working with it?

**Comment by alanggdev** [comment]
I have the same problem without J/REI with fabric 1.21, I just can't craft any hammers

**Comment by krispyzaza** [comment]
I'm using REI and no recipes are showing.

**Comment by 1xsabo** [comment]
I have the exact problem you can use them if you get them from creative but you cant craft them or see their recipes.

**Comment by MichaelHillcox** [comment]
Fixed and should be getting shipped as we speak

**Comment by kimleeseok** [comment]
크리에이티브 모드에서 찾아서 쓰려고했는데, 
Internal Exception: io.netty.handler.codec.decoder exceptoon: Failed to decode packet 'serverbound/minecraft: set_creative_mode_slot 
이렇게 떠요 이것도 지금 문제가 있을까요?
