### ISSUE TITLE
I can't enchant my hammer

### ISSUE THREAD

**Issue by Matteomac81888** [nanite/JustHammers#29]
### Minecraft Version

1.21

### Modloader

fabric-0.15.11

### Mod version

21.0.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

i have lost it

### Steps to reproduce the issue

1 take a hammer 2 take an enchanting table 3 try to enchant

### Description of the issue you are having

I can't enchant hammer in the enchanting table or in the anvil, if I try to pres "U" with jei nothing happens (meaning you can't do anything with hammers and you can't even enchant it

### Information

- [x] I have provided as much information as possible

**Comment by Pufty** [comment]
Same thing here. Maybe this is connected? - 
"Reference map 'just-hammers-common-refmap.json' for justhammers-common.mixins.json could not be read. If this is a development environment you can ignore this message"

**Comment by duskingtide** [comment]
Seconding. Also unable to apply an enchanted book (efficiency III) to the hammer using an anvil.
