### ISSUE TITLE
Change the Hammer from object type to combat type.

### ISSUE THREAD

**Issue by JloorDev** [nanite/JustHammers#30]
### Feature Description

I was testing the mod and it is really incredible, but there is something that I dislike a little and that is the fact that the player holds the hammer as if it were a normal object instead of as a combat object.
![Minecraft Screenshot 2024 06 21 - 23 08 03 55](https://github.com/nanite/JustHammers/assets/84237119/edb01415-93e4-4d31-beca-2de5c1a210b5)
![Minecraft Screenshot 2024 06 21 - 23 08 19 08](https://github.com/nanite/JustHammers/assets/84237119/6ee3bee8-b7a7-45e9-b731-4067e7a99010)

**Comment by makumaku1974** [comment]
preach
