### ISSUE TITLE
[Bug] Dirt destroyed by hammer

### ISSUE THREAD

**Issue by Ayyavazi** [nanite/JustHammers#35]
### Minecraft Version

1.21

### Modloader

Fabric, most recent

### Mod version

20.0.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

No log generated 

### Steps to reproduce the issue

1. Mine a pickaxe type block like stone with dirt/sand etc in the targeted 3x3. 2. Dirt/sand destroyed.

### Description of the issue you are having

Dirt/sand/gravel should not be destroyed by a hammer since they aren't destroyed by a pickaxe.

### Information

- [X] I have provided as much information as possible

**Comment by HatabyMC** [comment]
I am using version 1.20.1 of forge how can I implement the use of breaking dirt and sand blocks
