### ISSUE TITLE
[Issue] Crash on startup - Fabric 1.21

### ISSUE THREAD

**Issue by Shadowdane** [nanite/JustHammers#38]
### Minecraft Version

1.21

### Modloader

fabric loader 0.16.0

### Mod version

21.0.2

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

https://mclo.gs/8XYQ6ov 

### Steps to reproduce the issue

1.  Launch game
2.  Wait for crash

### Description of the issue you are having

Mod crashes on loading, this isn't a mod conflict.   Mod also crashes when it's the only mod installed.

Additional crash log with only Just Hammers loaded:  https://mclo.gs/Tvsf796  

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Interesting, thanks for the report. I'll look into this later today

**Comment by MichaelHillcox** [comment]
This should be fixed as of `21.0.3`. Please let me know if this is still broken
