### ISSUE TITLE
[Feature Request] : Faithful compatible resolution (texture pack)

### ISSUE THREAD

**Issue by Arch23-tech** [nanite/JustHammers#40]
### Feature Description

**Hello there 👋** 

Mr. nanite and Mikey you know faithfull is the most used texture pack in Minecraft history beside vanilla default textures......

Since the hammer textures a bit vanilla friendly, it will be very helpful of you to provide us a revamp to the resolution of textures (32 by 32) at least or even creating a distinct (32 by 32) resolution resource pack instead.

**_Plz for the love of God & Minecraft, I hope you don't disappoint us_**

**Comment by MichaelHillcox** [comment]
This is something someone else would have to support, this isn't something I would support first hand.
